version: "3.7"

services:
  registry:
    hostname: registry
    image: sharp6292/mcadesigns-registry:latest
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      PASS: ${DOCKER_PASS}

    restart: always

    volumes:
      - docker_data:/var/lib/registry


volumes:
  docker_data:

networks:
    default:
        external:
            name: sharpnet
