version: 2.1

orbs:
  docker: sharptools/docker@volatile
  sharpcd: sharptools/sharpcd@volatile

jobs:
  deploy:
    docker:
      - image: cimg/base:2020.01

    steps:
      - sharpcd/install

      - run:
          name: "Setup Env"
          command: |
            echo "DOCKER_PASS=${DOCKER_PASS}" > .env
            echo "DOCKER_USER=${DOCKER_USER}" >> .env
            echo "SHARPDOMAINS=${SHARPDOMAINS}" >> .env

      - sharpcd/deploy

workflows:
  version: 2
  workflow:
    jobs:
      - docker/build_wait:
          context: General
          image: sharp6292/registry:latest


      - deploy:
          context: General
          requires:
            - docker/build_wait

          filters:
            branches:
              only: main